export const authActionType = {
  AUTH_ON_INIT: 'AUTH_ON_INIT',
  AUTH_ON_SUCCESS: 'AUTH_ON_SUCCESS',
  AUTH_ON_ERROR: 'AUTH_ON_ERROR',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
};
