export const authActionType = {
  AUTH_ON_INIT: 'AUTH_ON_INIT',
  AUTH_ON_SUCCESS: 'AUTH_ON_SUCCESS',
  AUTH_ON_ERROR: 'AUTH_ON_ERROR',
  AUTH_REGISTER_INIT: 'AUTH_REGISTER_INIT',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
  AUTH_LOGIN_INIT: 'AUTH_LOGIN_INIT',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  CLEAN_ERROR: 'CLEAN_ERROR',
};
