export const chatActionType = {
  FETCH_CHATS_INIT: 'FETCH_CHATS_INIT',
  FETCH_CHATS_SUCCESS: 'FETCH_CHATS_SUCCESS',
  CREATE_CHAT_SUCCESS: 'CREATE_CHAT_SUCCESS',
  JOIN_CHAT_SUCCESS: 'JOIN_CHAT_SUCCESS',
  REFRESH_STATE_WHEN_CREATE_CHAT: 'REFRESH_STATE_WHEN_CREATE_CHAT',
  CLEAN_STATE: 'CLEAN_STATE',
  SET_ACTIVE_CHAT: 'SET_ACTIVE_CHAT',
  CHATS_UPDATE_USER_STATE: 'CHATS_UPDATE_USER_STATE',
  SEND_MESSAGE: 'SEND_MESSAGE',
  CHATS_SET_MESSAGES: 'CHATS_SET_MESSAGES',
};
